version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile_web
    command: gunicorn --bind 0.0.0.0:5000 app:app
    restart: always
    expose:
      - 5000
    volumes:
      - ./web/:/web/
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    volumes:
      - ./certbox/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
